apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${NAME}
  labels:
    app: ${NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${NAME}
  template:
    metadata:
      labels:
        app: ${NAME}
    spec:
      containers:
        - name: ${NAME}
          image: ${IMAGE}
          ports:
            - containerPort: ${PORT}
          resources:
            requests:
              cpu: "10m"
              memory: "24Mi"
            limits:
              cpu: "100m"
              memory: "64Mi"
